version: '3.8'

services:
  web:
    build:
      context: .  # 指定 Dockerfile 所在的目录
      dockerfile: Dockerfile  # 指定 Dockerfile 文件名（如果文件名不是默认的 Dockerfile，需要明确指定）
    ports:
      - "80:80"  # 将容器的 80 端口映射到宿主机的 80 端口
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # 如果需要动态更新 Nginx 配置文件
    networks:
      - webnet

networks:
  webnet: